package com.cgcreativesolutions.sampledadosabertosdacamera.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006B26)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF008732)
val onPrimaryContainerLight = Color(0xFFF7FFF2)
val secondaryLight = Color(0xFF755B00)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFCC29)
val onSecondaryContainerLight = Color(0xFF705700)
val tertiaryLight = Color(0xFF00327D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF0047AB)
val onTertiaryContainerLight = Color(0xFFA5BDFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF4FCEF)
val onBackgroundLight = Color(0xFF171D16)
val surfaceLight = Color(0xFFF4FCEF)
val onSurfaceLight = Color(0xFF171D16)
val surfaceVariantLight = Color(0xFFD9E6D4)
val onSurfaceVariantLight = Color(0xFF3E4A3D)
val outlineLight = Color(0xFF6E7B6B)
val outlineVariantLight = Color(0xFFBDCAB9)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B322A)
val inverseOnSurfaceLight = Color(0xFFECF3E7)
val inversePrimaryLight = Color(0xFF65DF76)
val surfaceDimLight = Color(0xFFD5DCD0)
val surfaceBrightLight = Color(0xFFF4FCEF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF6EA)
val surfaceContainerLight = Color(0xFFE9F0E4)
val surfaceContainerHighLight = Color(0xFFE3EADE)
val surfaceContainerHighestLight = Color(0xFFDDE5D9)

val primaryDark = Color(0xFF65DF76)
val onPrimaryDark = Color(0xFF003911)
val primaryContainerDark = Color(0xFF23A646)
val onPrimaryContainerDark = Color(0xFF002006)
val secondaryDark = Color(0xFFFFEDC6)
val onSecondaryDark = Color(0xFF3D2E00)
val secondaryContainerDark = Color(0xFFFFCC29)
val onSecondaryContainerDark = Color(0xFF705700)
val tertiaryDark = Color(0xFFB1C5FF)
val onTertiaryDark = Color(0xFF002C70)
val tertiaryContainerDark = Color(0xFF0047AB)
val onTertiaryContainerDark = Color(0xFFA5BDFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0E150E)
val onBackgroundDark = Color(0xFFDDE5D9)
val surfaceDark = Color(0xFF0E150E)
val onSurfaceDark = Color(0xFFDDE5D9)
val surfaceVariantDark = Color(0xFF3E4A3D)
val onSurfaceVariantDark = Color(0xFFBDCAB9)
val outlineDark = Color(0xFF879484)
val outlineVariantDark = Color(0xFF3E4A3D)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDDE5D9)
val inverseOnSurfaceDark = Color(0xFF2B322A)
val inversePrimaryDark = Color(0xFF006E27)
val surfaceDimDark = Color(0xFF0E150E)
val surfaceBrightDark = Color(0xFF343B33)
val surfaceContainerLowestDark = Color(0xFF091009)
val surfaceContainerLowDark = Color(0xFF171D16)
val surfaceContainerDark = Color(0xFF1B211A)
val surfaceContainerHighDark = Color(0xFF252C24)
val surfaceContainerHighestDark = Color(0xFF30372E)







